# Generated by Django 3.2.6 on 2021-08-07 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matcher', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='email',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='candidate',
            name='mobile',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
