# Generated by Django 3.2.6 on 2021-08-07 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matcher', '0002_auto_20210807_2149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='email',
            field=models.CharField(default=None, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='mobile',
            field=models.CharField(default=None, max_length=255, unique=True),
        ),
    ]
